version: "3.9"
services:
  nem12:
    build: .
    image: nem12-meter-readings:latest
    command: ["--input-dir", "/data/in", "--output-dir", "/data/out", "--logs-dir", "/_logs"]
    volumes:
      - ./data:/data
